### ISSUE TITLE
Support for sample weights in Double Machine Learning Estimators

### ISSUE THREAD

**Issue by vasilismsr** [microsoft/EconML#100] opened 2019-10-02 09:18 UTC
When samples represent summary statistics of many observations, then we need to pass in weights and variance properties of each sample. This will affect model fitting and inference.

**Comment by kbattocchi** [comment] 2019-10-02 13:18
@vasilismsr Is there anything needed for this other than what's already being added in #75?

**Comment by kbattocchi** [comment] 2019-10-02 13:24
@vasilismsr  See also #26

**Comment by kbattocchi** [comment] 2019-10-02 15:41
Closing since this is basically a duplicate of #26.

**Closed** 2019-10-02 15:41 UTC
Labels: enhancement
