### ISSUE TITLE
Index Error in predicting CATE with LinearCateEstimator and  DMLCateEstimator

### ISSUE THREAD

**Issue by divyat09** [microsoft/EconML#85] opened 2019-08-04 11:40 UTC
I am facing an error on estimating conditional average treatment using the LinearCateEstimator(). I am following the example given in the documentation: https://econml.azurewebsites.net/spec/api.html#api-of-conditional-average-treatment-effect-package

**Code:**
est = LinearCateEstimator()
est.fit(y, T, X, W,Z)
print( est.effect(T0_test , T1_test, X))

**est.effect(T0_test , T1_test, X) results in the following error:**

IndexError                                Traceback (most recent call last)
<ipython-input-27-6684c14d42ea> in <module>
      1 est = LinearCateEstimator()
      2 est.fit(y, T, X, W)
----> 3 print( est.effect(T0_test , T1_test, X))

~/.local/lib/python3.6/site-packages/econml/cate_estimator.py in effect(self, X, T0, T1)
    148         #       should it be possible to promote them to 2D arrays if that's what we saw during training?
    149         eff = self.const_marginal_effect(X)
--> 150         m = shape(eff)[0]
    151         if ndim(T0) == 0:
    152             T0 = np.repeat(T0, m)

**IndexError: tuple index out of range**

Each of the T0_test, T1_test, X have the shape: (6500, 1)

I am not able to understand what leads to this error. 

Also, I have faced issues in predicting CATE using  **DMLCateEstimator** 

**est.effect(T0_test , T1_test, X)  results in the following error for DMLCateEstimator:**

python-input-30-ee269e75ba5f> in <module>
      1 est1 = DMLCateEstimator(model_y=LassoCV(), model_t=LassoCV())
      2 est1.fit(Y, T, X, W)
----> 3 pred1= est1.effect(X, T0_test, T1_test)
      4 print(pred1)
      5 # est2 = DMLCateEstimator(model_y=RandomForestRegressor(),model_t=RandomForestRegressor())

~/.local/lib/python3.6/site-packages/econml/dml.py in effect(self, X, T0, T1)
    137             T0 = self._one_hot_encoder.transform(reshape(self._label_encoder.transform(T0), (-1, 1)))[:, 1:]
    138             T1 = self._one_hot_encoder.transform(reshape(self._label_encoder.transform(T1), (-1, 1)))[:, 1:]
--> 139         return super().effect(X, T0, T1)
    140 
    141     def score(self, Y, T, X=None, W=None):

~/.local/lib/python3.6/site-packages/econml/cate_estimator.py in effect(self, X, T0, T1)
    159         if ndim(eff) == ndim(dT):  # y is a vector, rather than a 2D array
    160             einsum_str = einsum_str.replace('y', '')
--> 161         return np.einsum(einsum_str, eff, dT)
    162 
    163     def marginal_effect(self, T, X=None):

<__array_function__ internals> in einsum(*args, **kwargs)

~/.local/lib/python3.6/site-packages/numpy/core/einsumfunc.py in einsum(*operands, **kwargs)
   1354     # If no optimization, run pure einsum
   1355     if optimize_arg is False:
-> 1356         return c_einsum(*operands, **kwargs)
   1357 
   1358     valid_einsum_kwargs = ['out', 'dtype', 'order', 'casting']

**ValueError: einstein sum subscripts string contains too many subscripts for operand 0**

**Comment by kbattocchi** [comment] 2019-08-05 14:20
@divyat09 Thanks for the bug report, and sorry for not catching this ourselves.  The issue is that we made a breaking change in our 0.3 release to reorder the arguments to `effect` (now you should call `est.effect(X, T0_test, T1_test)`, or in the common case where you've got a one-dimensional treatment and `T0` is all 0s and `T1` is all 1s, you can just call `est.effect(X)`).  Unfortunately we appear to have forgotten to update the page of the spec you linked to.

**Comment by divyat09** [comment] 2019-08-05 14:36
@kbattocchi  Thanks for your reply. **est.effect(X)** works for the DoubleMLCateEstimator in single-dimensional treatment case and **est.effect(X,T0_test, T1_test)** works for the general treatment case

I still believe there are issues with effect prediction using LinearCateEstimator. I tried both combinations: **est.effect(X)** and **est.effect(X, T0_test, T1_test)** but it gives the same Index Error as before. This occurs for both the single-dimensional and the general dimensional treatment case.


Another minor bug is that **est.effect(X,T0_test, T1_test)**  does not work for the single-dimensional treatment case on using DoubleMLCateEstimator

**Comment by kbattocchi** [comment] 2019-08-05 15:13
@divyat09 
For the first problem, that's because `LinearCateEstimator` isn't intended to be used directly (it should have been an abstract class to prevent it from being used but we failed to specify the `abc.ABCMeta` metaclass in the current release - this will be fixed in our next release).

But I'm surprised by your last comment - can you give a short example where `est.effect(X, T0_test, T1_test)` fails?  This works for me on the 0.4 release:

    import numpy as np
    from econml.dml import DMLCateEstimator
    from sklearn.linear_model import LinearRegression
    X = np.random.normal(size=(10,1))
    T = np.random.normal(size=(10,1)) # also works with size=(10,) as long as np.zeros and np.ones calls below are changed accordingly
    Y = np.random.normal(size=(10,1))
    est = DMLCateEstimator(model_t=LinearRegression(), model_y=LinearRegression())
    est.fit(Y, T, X)
    est.effect(X, np.zeros((10,1)), np.ones((10,1)))

**Comment by divyat09** [comment] 2019-08-05 15:40
@kbattocchi  My bad, I guess I made some error,  **est.effect(X, T0_test, T1_test)** works for singe dimensional treatment cases too. Thanks for your help!

**Comment by kbattocchi** [comment] 2019-08-05 15:42
@divyat09 No problem, and thanks for flagging the issue with our documentation.  Please let us know if you run into any other issues.

**Comment by divyat09** [comment] 2019-08-05 15:50
@kbattocchi  Actually there is a weird case in which it seems to go wrong, so I have a pandas dataframe from where I load the data and estimate using the code below:

print(Y.shape, T.shape, X.shape, W.shape, T0_test.shape, T1_test.shape)
est1 = DMLCateEstimator(model_y=LassoCV(), model_t=LassoCV())
est1.fit(Y, T, X, W)
pred1= est1.effect(X, T0_test, T1_test)

Here is the output of the above code:

(6500,) (6500,) (6500, 1) (6500, 22) (6500, 1) (6500, 1)
ValueError                                Traceback (most recent call last)
<ipython-input-71-665f38cb4c9d> in <module>
      2 est1 = DMLCateEstimator(model_y=LassoCV(), model_t=LassoCV())
      3 est1.fit(Y, T, X, W)
----> 4 pred1= est1.effect(X, T0_test, T1_test)

~/.local/lib/python3.6/site-packages/econml/dml.py in effect(self, X, T0, T1)
    137             T0 = self._one_hot_encoder.transform(reshape(self._label_encoder.transform(T0), (-1, 1)))[:, 1:]
    138             T1 = self._one_hot_encoder.transform(reshape(self._label_encoder.transform(T1), (-1, 1)))[:, 1:]
--> 139         return super().effect(X, T0, T1)
    140 
    141     def score(self, Y, T, X=None, W=None):

~/.local/lib/python3.6/site-packages/econml/cate_estimator.py in effect(self, X, T0, T1)
    159         if ndim(eff) == ndim(dT):  # y is a vector, rather than a 2D array
    160             einsum_str = einsum_str.replace('y', '')
--> 161         return np.einsum(einsum_str, eff, dT)
    162 
    163     def marginal_effect(self, T, X=None):

<__array_function__ internals> in einsum(*args, **kwargs)

~/.local/lib/python3.6/site-packages/numpy/core/einsumfunc.py in einsum(*operands, **kwargs)
   1354     # If no optimization, run pure einsum
   1355     if optimize_arg is False:
-> 1356         return c_einsum(*operands, **kwargs)
   1357 
   1358     valid_einsum_kwargs = ['out', 'dtype', 'order', 'casting']

ValueError: einstein sum subscripts string contains too many subscripts for operand 0


Now, it might be because of the case Y and T are of shape (6500,). But if I reshape them to (6500,1), then I get an error in the **est.fit(Y,T,X,W)** method:

(6500, 1) (6500, 1) (6500, 1) (6500, 22) (6500, 1) (6500, 1)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-73-665f38cb4c9d> in <module>
      1 print(Y.shape, T.shape, X.shape, W.shape, T0_test.shape, T1_test.shape)
      2 est1 = DMLCateEstimator(model_y=LassoCV(), model_t=LassoCV())
----> 3 est1.fit(Y, T, X, W)
      4 pred1= est1.effect(X, T0_test, T1_test)

~/.local/lib/python3.6/site-packages/econml/dml.py in fit(self, Y, T, X, W)
     95                 T_res[test_idxs] = T_test - self._models_t[idx].predict(X_test, W_test)[:, 1:]
     96             else:
---> 97                 T_res[test_idxs] = T_test - self._models_t[idx].predict(X_test, W_test)
     98             self._models_y[idx].fit(X_train, W_train, Y_train)
     99             Y_res[test_idxs] = Y_test - self._models_y[idx].predict(X_test, W_test)

ValueError: shape mismatch: value array of shape (3250,3250) could not be broadcast to indexing result of shape (3250,1)

**Comment by kbattocchi** [comment] 2019-08-05 16:00
@divyat09 It looks like in the first case `T` is a vector (shape `(6500,)`) while `T0` and `T1` are one-column arrays (shape `(6500,1)`).  I believe if you make them all vectors then the code should work.

However, you're right that making them all one-column arrays should work, but doesn't.  I'll try to take a closer look at what's going wrong.

**Comment by kbattocchi** [comment] 2019-08-05 17:16
@divyat09 The immediate cause of the last issue is that `LassoCV` (and `Lasso`, but not `LinearRegression`) will return a vector from `predict` even when the input to `fit` was a one-column array, which our code doesn't expect.

I'll open a separate issue covering this; it seems like something we ought to be able to detect and work around.  Thanks again for the feedback!

**Closed** 2019-08-14 13:26 UTC
